---
title: "README"
author: "Emily Lacroix"
date: "7/3/2020"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This repo contains the code and data to reproduce all results and figures in the 2020 Biogeochemistry publication: **Effects of Moisture and Physical Disturbance on Pore-Scale Oxygen Content and Anaerobic Metabolisms in Upland Soils**. 

`TempeCell_MasterSpreadsheet.xlsx` contains all of the data used in analyses as well as a README tab explaining data types and units. The R Markdown files are configured to read directly from this master spreadsheet on the user's desktop. 

Each RMarkdown file regenerates all results and figures used in the manuscript. The `.md` files in this repo show formatted code output. The `.Rmd` files can be downloaded to run and edit on your lcoal machine. 

`DO_publication_scriptv3.md` shows data processing for DO data. 
`FeMnAnalysis_v2.md` shows data processing for Fe and Mn reduction. 
`GHG_publication_figures_v2.md` shows data processing for CO2 flux data.
`PorVolumeProcessing_v2.md` shows data processing for pore volume analysis.
`OtherAnalyses.md` shows data processing for ancillary data such as dissolved organic carbon, pH, etc. 

Please contact the corresponding author(s) with questions or enhanced access. 


